### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by HYZ199** [wzhlearning/fNIRS-Transformer#1]
Where is the code

**Comment by wzhlearning** [comment]
@HYZ199  Thank you for noticing our work. Currently, we are in the winter vacation phase, but all the data and codes are stored in the lab computers. We are cleaning up the code and will release it in the near future.

**Comment by HYZ199** [comment]
谢谢！您的邮件我已收到，我会尽快处理。

**Comment by lingxiangliao** [comment]
可以提供t-SNE的代码吗，或者是讲述下对于各个方法，比如lstm使用tSNE的data和label怎么对应？

**Comment by HYZ199** [comment]
谢谢！您的邮件我已收到，我会尽快处理。

**Comment by wzhlearning** [comment]
@lingxiangliao 您好！如LSTM对二分类进行t-SNE，一次性将全部data和对应的label送入训练好的LSTM，取最后的全连接层送入sklearn.manifold.TSNE()函数得到2D特征，这个2D特征的类别与label的顺序是一致的(比如，2D特征的第一行的类别就是label的第一行)，用for循环将不同label的2D特征单独保存，最后绘制散点图。另外，网上关于t-SNE可视化MNIST数据集的例子也可以参考。

**Comment by HYZ199** [comment]
谢谢！您的邮件我已收到，我会尽快处理。

**Comment by HYZ199** [comment]
谢谢！您的邮件我已收到，我会尽快处理。

**Comment by CXVV0601** [comment]
您好，能否发一下对比网络（SVM,CNN,LSTM)的代码呢

**Comment by HYZ199** [comment]
谢谢！您的邮件我已收到，我会尽快处理。

**Comment by wzhlearning** [comment]
@CXVV0601 您好，感谢关注我们的工作，您可以通过论文（一作）邮箱联系我。
